### PR TITLE
Add `Derive` Feature to `Clap` in `coffee_httpd` `Cargo.toml`

### LINKED ISSUE #215: Compilation Errors: Cannot Find derive macro Parser and clap Attribute
I encountered compilation errors while trying to install `coffee_httpd`. The errors seem to be related to the use of the **`clap`** crate and the **`Parser`** trait. 

Command used: ```cargo install --path coffee_httpd```

Below is a summary of the errors:
```
error: cannot find derive macro `Parser` in this scope
error: cannot find attribute `clap` in this scope
error[E0599]: no function or associated item named `parse` found for struct `HttpdArgs` in the current scope

error: could not compile `coffee_httpd` (bin "coffee_httpd") due to 10 previous errors; 1 warning emitted
error: failed to compile `coffee_httpd v0.1.0 (/home/royalpinto007/coffee/coffee_httpd)`, intermediate artifacts can be found at `/home/royalpinto007/coffee/target`
```

### PR DESCRIPTION
**Pull request by tareknaser**
## Changes:
- Added the `Derive` feature to clap in `coffee_httpd/Cargo.toml`
## Description:
This pull request resolves an issue where the `coffee_httpd` crate was unable to compile on its own. The changes specifically adds the `Derive` feature to clap in the `coffee_httpd/Cargo.toml` file.
Here is a related discussion https://github.com/rust-lang/cargo/issues/11551 

Fixes #215

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
LGTM
